### PR TITLE
JSBI BigInt in read.js #74

### PR DESCRIPTION
**Pull request by bencmbrook**
Original PR #74 from @vincaslt

### CODE REVIEW

**Review by michaelfarrell76 — COMMENTED** [review]
looks good, dont really know whats going on tho, maybe get @eligrey to take a look

**Review by eligrey — CHANGES_REQUESTED** [review]
We should be using real BigInts when supported natively and fallback to JSBI as needed. Only ever using JSBI may decrease performance noticeably.

**Comment by bencmbrook** [comment]
I suggest keeping JSBI and polyfilling to bigint when it’s shipped widely. Interesting discussion here https://twitter.com/privacypros/status/1309289031419793410?s=21

**Comment by eligrey** [comment]
JSBI is more of the polyfill in the situation. I can change the PR to use real BigInt when supported and fallback to JSBI

**Comment by eligrey** [comment]
It seems like we can use https://github.com/GoogleChromeLabs/babel-plugin-transform-jsbi-to-bigint to auto-transform JSBI to BigInt.

I'm not sure if there is any reason preventing us from using the polyfill dynamically so that BigInt is used when supported.

**Comment by bencmbrook** [comment]
Okay, switching this to merge to a bigger JSBI feature branch

**Pull request merged**
