### PR TITLE
Set up testing and codecov

### LINKED ISSUE #5: Code coverage?
Could be nice / useful?

### PR DESCRIPTION
**Pull request by bencmbrook**
- Using ~Ava~ tape for testing #3
- Using Istanbul/NYC/Codecov for test coverage closes #5
- Using airtap for browser testing
- Using Sauce Labs for cross-browser testing (submitted an application for unlimited runs with open source)
- All on Travis CI.

- Eslint (Airbnb) and Editorconfig

### CODE REVIEW

**Comment by jimmywarting** [comment]
Saw that you imported eslint
All code that I have written so far follows [StandardJS](https://standardjs.com/)

**Comment by jimmywarting** [comment]
I was working on a patch to `/write.js` that didn't use private class fields... At least then you don't have to use a transpiler. (was looking into making the script working in FF and other browsers)

**Comment by bencmbrook** [comment]
@jimmywarting do you mind if we use Airbnb's lint rules? Our team uses them in all projects, so it's nice to have that consistency on our end :)

**Comment by bencmbrook** [comment]
Also, I'm gonna take a stab at spinning up in-browser testing

**Comment by jimmywarting** [comment]
> @jimmywarting do you mind if we use Airbnb's lint rules? Our team uses them in all projects, so it's nice to have that consistency on our end :)

Since this is a organization and all your teammates use it i would be fine with it if you would like  consistency. to quote StandardJS:

> There are lots of debates online about tabs vs. spaces, semicolon vs no colons, etc. that will never be resolved. These debates just distract from getting stuff done. At the end of the day you have to 'just pick something' - StandardJS

Thats kinda my philosophy too. But I also tend to look the other way and not use any linter at all. works ok for small project. My main reasoning:

- There are a lot good things we can do before we debate on what we should use.
- We might end up turning off rules because sometimes cuz it isn't what we want.
- New syntax don't works with linters
- it just adds extra dependency and build time
- you end up researching "what is wrong with my code, how to make linters happy?" and sending new bug reports to something that is wrong or not supported like when new syntax becomes available
- linters don't know if i'm working in node or the browsers so it don't know whats is available globally 

My principle is only:

- Code it so it looks consistent with the rest of the code.
- Have somewhere in the back of you head some guidelines, eg like the airbnb or StandardJS rules
doesn't have to be those or everything they rule out. 

But i must admit, Linters is a good tool for the quality of the code. But you must put some more effort into it and also keep it up to date. But to me it's not worth it

**Comment by eligrey** [comment]
In response to "New syntax don't works with linters": eslint is actively maintained and has a strong development community around it. I don't think we will have to worry about eslint lagging behind in syntax support.

**Comment by jimmywarting** [comment]
When I do decide to include linters into my projects i always go with StandardJS. Main reason is 

> it saves you time in three ways:
> 
> - No configuration. 
> - The easiest way to enforce consistent style in your project. Just drop it in.
> - Automatically format code. Just run standard --fix and say goodbye to messy or inconsistent code.
Catch style issues & programmer errors early. Save precious code review time by eliminating back-and-forth between reviewer & contributor.
No decisions to make. No .eslintrc, .jshintrc, or .jscsrc files to manage. It just works.

StandardJS is more like styleguide where as airbnb is all the things StandardJS with the addition of things you can/can't use. like my most hatred one: can't use for loops generator and iterators. they say that higher order functions should be used instead like forEach, map, filter should be used

i hate things like that that applies rules that can't be used. i think a linter should only help me spot errors and not telling me what i can and can't do

**Comment by jimmywarting** [comment]
now when i look more into the list i disagree with quite a few rules airbnb use
for instance 

Use the literal syntax for array creation. eslint: no-array-constructor
```
// bad
const items = new Array();

// good
const items = [];
```

how about when you know the length of the array?
using `new Array(n)` adding things to an array that don't need to expand is faster

**Comment by bencmbrook** [comment]
Okay cool. Let's start with Airbnb and disable rules as needed. There are indeed some rules that don't fit with all projects, but generally it's a fine baseline.

**Pull request merged**
